### PR TITLE
Add a method to delete a log file

### PR DESCRIPTION
**Pull request by airxnoor**
In order to allow users (of this library) to be able to delete log files across different OSs, we've added a cross-platform `delete(path)` method to remove a log file from the system. This is added only to `FileLoggerFacility`.

### CODE REVIEW

**Comment by eirikvaa** [comment]
@airxnoor Would it make sense to extend the API with a convenience function to delete all log files older than a certain date, for instance, older than today?

**Review by eirikvaa — APPROVED** [review]
I had one suggestion for the API, but this seems reasonable to me 👍

**Comment by airxnoor** [comment]
> @airxnoor Would it make sense to extend the API with a convenience function to delete all log files older than a certain date, for instance, older than today?

I actually had that function added to the interface, and then I thought: We'll just add it when we need it. What do you think?

**Comment by eirikvaa** [comment]
> > @airxnoor Would it make sense to extend the API with a convenience function to delete all log files older than a certain date, for instance, older than today?
> 
> I actually had that function added to the interface, and then I thought: We'll just add it when we need it. What do you think?

It sounds like something that would be useful from the start, but I'm fine with taking it later :-)

**Pull request merged**
