### PR TITLE
Use TOML versioning

### PR DESCRIPTION
**Pull request by eirikvaa**

### CODE REVIEW

**Comment by eirikvaa** [comment]
I noticed https://github.com/Airthings/KmpLog/pull/11, but that PR is using the Airthings version catalog, which there seemed to be some concerns about, so this PR only adopts TOML versioning but keeps the dependencies in the library.

**Review by sylwester-zielinski — APPROVED** [review]

**Comment by eirikvaa** [comment]
@sylwester-zielinski I forgot to test how this integrates locally, and it complained about too old AGP and Gradle versions, so I'll push those updates as well.

**Comment by sylwester-zielinski** [comment]
You need to switch Gradle to use Java 17 in AS settings. 

But yeah, also updating libraries would be nice.

**Comment by eirikvaa** [comment]
> You need to switch Gradle to use Java 17 in AS settings.
> 
> But yeah, also updating libraries would be nice.

Yup, I checked and AS is using Java 17. 👍 

I can update the rest of the dependencies in a later PR.

**Pull request merged**
